create table public.bo_repository_threshold_activity (
  id bigint generated always as identity not null,
  created_at timestamp with time zone not null default now(),
  limit_containers_low integer null,
  limit_containers_low_last_update timestamp with time zone null,
  limit_containers_medium integer null,
  limit_containers_medium_last_update timestamp with time zone null,
  limit_containers_high integer null,
  limit_containers_high_last_update timestamp with time zone null,
  limit_containers_critical integer null,
  limit_containers_critical_last_update timestamp with time zone null,
  limit_sast_low integer null,
  limit_sast_low_last_update timestamp with time zone null,
  limit_sast_medium integer null,
  limit_sast_medium_last_update timestamp with time zone null,
  limit_sast_high integer null,
  limit_sast_high_last_update timestamp with time zone null,
  limit_sast_critical integer null,
  limit_sast_critical_last_update timestamp with time zone null,
  limit_sca_low integer null,
  limit_sca_low_last_update timestamp with time zone null,
  limit_sca_medium integer null,
  limit_sca_medium_last_update timestamp with time zone null,
  limit_sca_high integer null,
  limit_sca_high_last_update timestamp with time zone null,
  limit_sca_critical integer null,
  limit_sca_critical_last_update timestamp with time zone null,
  name_repository text null,
  owner text null,
  url_variables text null,
  constraint bo_repository_threshold_activity_pkey primary key (id)
) TABLESPACE pg_default;


create table public.bo_repository_workflows_activity (
  id bigint generated always as identity not null,
  created_at timestamp with time zone not null default now(),
  have_checkmarx boolean null,
  have_continuous_build boolean null,
  have_conjur boolean null,
  have_change_velocity boolean null,
  have_release_sharedpoint boolean null,
  have_release_github boolean null,
  have_validate_pr boolean null,
  name_repository text null,
  id_type_repository integer null,
  owner text null,
  url_workflows text null,
  constraint bo_repository_workflows_activity_pkey primary key (id)
) TABLESPACE pg_default;